spring:
   mail:
    host: smtp.163.com
    username: zypyjy@163.com
    password: yjy1234
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
server:
  port: 8080