server:
  port: 8012
spring: 
  application: 
    name: yjy-mq
  cloud: 
      stream: 
       # default-binder: rabbit
        bindings: 
          event_yjy: 
        #    content-type: application/x-java-object
            group: ${spring.application.name}
         
#    
#  rabbitmq: 
#      addresses: 127.0.0.1:5672
#      username: admin_yjy
#      password: 123456
#      virtual-host: /yjy    
  rabbitmq: 
      host: 127.0.0.1
      port: 5672
      username: admin_yjy
      password: 123456
      virtualHost: /yjy    
#      binders: 
#         rabbit: 
#          type: rabbit
#          environment:
#            spring: 
#              rabbitmq: 
#                addresses: 127.0.0.1:5672
#                username: admin_yjy
#                password: 123456
#                virtual-host: /yjy
 